Fix css preview when not yet published.
tarosky/taro-custom-style pull request #7
Opened 2024-08-29 07:24 UTC by waviaei

Fix #5

2024-08-29 08:13 UTC, waviaei commented
クラシックエディター：
- publish 前のプレビュー → プレビュー画面に反映されるようになった
- publish 後 の更新プレビュー → プレビュー画面に反映されるようになった。ただし、プレビュー画面を開くだけではrevisionの自動保存がされないケースがあり、その場合は少し待つ必要あり。

ブロックエディター：
- publish 前のプレビュー → プレビュー画面に反映されるようになった
- publish 後 の更新プレビュー → プレビュー画面に反映されない

2024-08-29 12:33 UTC, fumikito requested changes
@waviaei エラーログの出力が残ってます。

2024-08-29 12:33 UTC, fumikito commented on includes/post-meta-box.php
> +		error_log( 'AAAAA' );
この行けしてください！

2024-08-30 03:34 UTC, waviaei commented on includes/post-meta-box.php
> +		error_log( 'AAAAA' );
ぎゃあ

2024-08-30 03:37 UTC, waviaei commented on includes/post-meta-box.php
> +		error_log( 'AAAAA' );
@fumikito 削除しました

2024-09-02 01:58 UTC, fumikito approved these changes
LGTM

2024-09-02 01:58 UTC, merged